apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/instance: vigobas-samtykke-frontend_rogfk_no
  fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/rogfk-no"
      - op: replace
        path: "/spec/env/0/value"
        value: "/beta/rogfk-no"
    target:
      kind: Application
      name: vigobas-samtykke-frontend
  - patch: |-
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/rogfk-no"
    target:
      kind: Application
      name: vigobas-samtykke-frontend

