apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no
resources:
  - ../../../base
patchesStrategicMerge:
  - ingress-route.yaml
commonLabels:
  app.kubernetes.io/name: vigobas-samtykke-frontend
  app.kubernetes.io/instance: vigobas-samtykke-frontend_rogfk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: samtykke-frontend
  app.kubernetes.io/part-of: vigobas
  fintlabs.no/team: bas
  fintlabs.no/org-id: rogfk.no