apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: vigobas-samtykke-frontend
  namespace: rogfk-no
spec:
  orgId: rogfk.no
  image: fintlabsacr.azurecr.io/vigobas-samtykke-frontend:latest
  imagePullPolicy: Always
  url:
    hostname: samtykke.vigoiks.no
    basePath: /beta/rogfk-no
  ingress:
    enabled: true
    middlewares:
      - vigobas-samtykke-frontend-sso