apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: vigobas-samtykke-frontend
  namespace: rogfk-no
  labels:
    app.kubernetes.io/name: vigobas-samtykke-frontend
    app.kubernetes.io/component: samtykke-frontend

spec:
  orgId: rogfk.no
  #image: fintlabsacr.azurecr.io/vigobas-samtykke-frontend:latest
  image: fintlabsacr.azurecr.io/vigobas-samtykke-frontend:1a49c5458e7fb2544cfab94b5d82462d76777300
  imagePullPolicy: Always
  url:
    hostname: samtykke.vigoiks.no
    basePath: /beta/rogfk-no
  ingress:
    enabled: true
    middlewares:
      - vigobas-samtykke-frontend-sso