apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: vigobas-samtykke-frontend
  namespace: rogfk-no
  labels:
    app.kubernetes.io/name: vigobas-samtykke-frontend
    app.kubernetes.io/instance: vigobas-samtykke-frontend_rogfk_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: samtykke-frontend
    app.kubernetes.io/part-of: vigobas
    fintlabs.no/team: bas
    fintlabs.no/org-id: rogfk.no
spec:
  orgId: rogfk.no
  image: fintlabsacr.azurecr.io/vigobas-samtykke-frontend:latest
  imagePullPolicy: Always
